name: IjarApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - run: |
          cd backend
          npm install
          cd ../frontend
          npm install
          npm run build
          cd ../backend
          # Ensure PM2 is installed globally
          npm install -g pm2
          # Restart the PM2 process
          pm2 restart 0
          # Save the PM2 process list
          pm2 save
          # Restart Nginx
          sudo service nginx restart
