name: IjarApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Check if backend package.json has changed
        id: check_backend_package_json
        run: |
          git fetch origin main
          backend_changed_files=$(git diff --name-only HEAD..origin/main backend/package.json)
          if [[ -n $backend_changed_files ]]; then
            echo "::set-output name=backend_changed::true"
          else
            echo "::set-output name=backend_changed::false"
          fi

      - name: Check if frontend package.json has changed
        id: check_frontend_package_json
        run: |
          git fetch origin main
          frontend_changed_files=$(git diff --name-only HEAD..origin/main frontend/package.json)
          if [[ -n $frontend_changed_files ]]; then
            echo "::set-output name=frontend_changed::true"
          else
            echo "::set-output name=frontend_changed::false"
          fi

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Backend Dependencies
        if: steps.check_backend_package_json.outputs.backend_changed == 'true'
        run: npm install
        working-directory: backend

      - name: Install Frontend Dependencies
        if: steps.check_frontend_package_json.outputs.frontend_changed == 'true'
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Manage PM2 and Nginx
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
